apiVersion: v1
kind: Namespace
metadata:
  name: notes
  labels:
    # API server rejects any pod in this namespace that doesn't meet the "restricted" profile
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
